---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: node:14
  commands:
    - npm install
- name: lint
  image: node:14
  commands:
    - npm run lint
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/task-metrics-service
    dry_run: true
    purge: true
trigger:
  event:
    - push
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/task-metrics-service
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
    - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/task-metrics-service
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: i6LLJ16wuUb8P0yvME1vd9Lyzu5kcf2k4BA2i/Rwa8NVwI5rPyYu2g==
---
kind: secret
name: docker_password
data: z3zaRwyWFm0OCOjQRFNVQ/l+JdLWDT6oqNI2jzeZQw8UCn3gge2nAlTabwwIzTAUpSAKd9xzNwXHZK1/n9cHTA==
---
kind: signature
hmac: a8de7370ec85a734768dd8bbc58a6f988c93ce33c9e40e4dc3945bfcb83a06a5

...
